export const districtes = [
    'Sants-Montjuïc', 
    'Sant Martí', 
    'Gràcia', 
    'Sant Andreu',
    'Ciutat Vella', 
    'Eixample', 
    'Sarrià-Sant Gervasi',
    'Horta-Guinardó', 
    'Nou Barris', 
    'Les Corts'
];

export const tipusNegoci = [
    'Serveis a les empreses i oficines', 
    'Activitats emmagatzematge',
    'Administració', 
    'Activitats de transport ', 
    'Vehicles',
    'Restaurants', 
    'Material equipament llar', 
    'Carn i Porc', 
    'Altres',
    'Peix i marisc', 
    'Floristeries', 
    'Fruites i verdures',
    'Drogueria i perfumeria',
    'Vestir', 
    'Ous i aus',
    'Pa, pastisseria i làctics',
    'Basars',
    'Plats preparats (no degustació)', 
    'Farmàcies PARAFARMÀCIA',
    'Ensenyament', 
    'Sense informació',
    'Souvenirs',
    'Reparacions (Electrodomèstics i automòbils)',
    'Autoservei / Supermercat',
    'Sanitat i assistència',
    'Sense informació - Havia tingut activitat (rètol)',
    'Finances i assegurances', 
    "serveis d'allotjament",
    'Bars / CIBERCAFÈ',
    'Equipaments culturals i recreatius',
    'En reforma',
    'Merceria',
    'Locals buits en venda i lloguer',
    'Arts gràfiques',
    "Centres d'estètica",
    'Calçat i pell',
    'Xocolateries / Geladeries / Degustació',
    'Activitats industrials',
    'Parament ferreteria',
    'Activitats immobiliàries',
    'Altres equipaments esportius',
    'Locals buits en lloguer',
    'Mobles i articles fusta i metall',
    'Fabricació tèxtil',
    'Locals buits en venda',
    'Perruqueries',
    'Tabac i articles fumadors',
    'Serveis de menjar take away MENJAR RÀPID',
    'Serveis Socials',
    'Associacions', 
    'Informàtica', 
    'Gimnàs /fitnes',
    'Activitats de transport i emmagatzematge',
    'Activitats de la construcció', 
    'Joguines i esports',
    'Llibres, diaris i revistes', 
    'Joieria, rellotgeria i bijuteria',
    'Grans magatzems i hipermercats',
    'Aparells domèstics',
    'Manteniment, neteja i similars',
    'Veterinaris / Mascotes',
    'Herbolaris, dietètica i NUTRICIÓ',
    'Bars especials amb actuació / Bars musicals / Discoteques /PUB',
    'Souvenirs i basars',
    'Begudes',
    'Pàrquings i garatges',
    'Tintoreries',
    'Fotografia',
    'Arranjaments',
    'Òptiques ',
    'Agències de viatge',
    'Segells, monedes i antiguitats',
    'Serveis de telecomunicacions',
    'Serveis de menjar i begudes',
    'Equipaments religiosos',
    'Combustibles i carburants',
    'Música',
    'Locutoris',
    'Maquinària',
    'Esports',
    'Òptiques i fotografia',
    'Altres', 'Altres ( per exemple VENDING)'
];